name: daily_scope_workspace
description: Daily Scope Flutter monorepo workspace
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

# Dart workspace configuration
workspace:
  - daily_scope
  - packages/common
  - packages/auth_module
  - packages/news_module
  - packages/weather_module



dev_dependencies:
  melos: ^4.1.0
